### ISSUE TITLE
Add CSS for printer friendly version

### ISSUE THREAD

**Issue by xapasnon** [JohnDoeInvest/ms-visualization#10]
The original idea was to include a PDF export. However, it might be the case that one wants to highlight one service in the cloud and print that view. And all browsers do PDF export.

So let's remove the unwanted parts: header, editor, footer 
And add pagebreaks after the services list, after the diagram and so on.

Here are some hints on how to achieve this: https://www.sitepoint.com/css-printer-friendly-pages/

**Comment by lamdoann** [comment]
It's done.

**Comment by lamdoann** [comment]
DONE
