### ISSUE TITLE
Add bounding box for text on icons and use this surface

### ISSUE THREAD

**Issue by xapasnon** [JohnDoeInvest/ms-visualization#12]
Effectively we should be able to do the same thing here as for the connectors - add a path with a specific name on each icon and use getbbox on that path to scale and position text.

**Comment by xapasnon** [comment]
Use the path "#description" as bounding box for text on each icon. Try to write as large as possible within the box. We'll modify the icons later.

**Comment by lamdoann** [comment]
DONE
