### ISSUE TITLE
Parse ENV variables and present in table

### ISSUE THREAD

**Issue by xapasnon** [JohnDoeInvest/ms-visualization#13]
In S12 we have updated the serviceDescriptions to include relevant ENV vars.

We want to add another table (similar to the one listing the microservices) below the SVG which has:
Name: and Description

The ENV vars are unique across the whole application. So only listed once in the list.

When a service is selected, the used ENV vars for that service is highlighted.

**Comment by lamdoann** [comment]
DONE
