### ISSUE TITLE
Add support for special microservice name GLOBAL

### ISSUE THREAD

**Issue by xapasnon** [JohnDoeInvest/ms-visualization#14]
When we added ENV vars to S12, we identified a number of them which are defined/used by the main server code, session code and/or helpers. I.e. not linked to a specific microservice.

After some discussions, we have decided to reserve the servicename GLOBAL for this purpose.

The GLOBAL microservice shall be treated/presented just like any other microservice, but with a special icon version. For development, copy the normal ms one.

**Comment by xapasnon** [comment]
Use the icon "icn-global"

**Comment by lamdoann** [comment]
DONE
