### ISSUE TITLE
Tweak REST API presentation with parentnode

### ISSUE THREAD

**Issue by xapasnon** [JohnDoeInvest/ms-visualization#16]
Currently, all microservices get a parent node for REST API. This should be changed so that:
- If there are 0 defined entries, no node is added
- If there are 1 defined entry, the entry is added directly without the parent/middle node
- If there are more entries, the parent node is added as now (collapsed) with the entries as children

**Comment by lamdoann** [comment]
DONE

**Comment by xapasnon** [comment]
Tested ok!
