### ISSUE TITLE
Support array of services

### ISSUE THREAD

**Issue by xapasnon** [JohnDoeInvest/ms-visualization#2]
The current code visualizes one service. Now, let's add support for multiple. I.e. an array of serviceDescription objects.

For testing, copy the existing data.json and just rename the service to "service2" and let it use the same topics/shared services.

**Comment by lamdoann** [comment]
I finished it. Please add any json url you want.
Sample url: https://raw.githubusercontent.com/lamdoann/serviceDescriptions/master/serviceDescription-0.json

**Comment by xapasnon** [comment]
Tested ok. I'll create a new issue in where the services/topics are to be re-used/unique across services, but I will consider this issue resolved to keep it clear.
