### ISSUE TITLE
Add GitHub search and load support

### ISSUE THREAD

**Issue by xapasnon** [JohnDoeInvest/ms-visualization#4]
As outlined in the goals for this project we want to keep the service description as close to the code as possible to make it more likely to be up to date. This will result in many "serviceDescription.json" files spread out in your repository. 

Add an input field and button "Find and load from GitHub" which uses the GitHub API (https://developer.github.com/v3/search/) to find all instances of serviceDescription.json in a repository and load them up into the editor/viewer.

**Comment by lamdoann** [comment]
I supported searching serviceDescription json file on the repo.
Currently, I temporarily used this repo: https://github.com/lamdoann/serviceDescriptions

**Comment by xapasnon** [comment]
Cannot get this to work. Please confirm what should be entered into the search field - the full URL that you provide as example then hit the search icon and it should load? 

Feel free to create the test files in the ms-visualize repository so we can use it as examples later on.

And when you do, I would prefer the following catalogue structure (which I think will be more commonly used than multiple service description files in one directory):
/test/fakeMicroservice1/serviceDescription.js
/test/fakeMicroservice2/serviceDescription.js

**Comment by lamdoann** [comment]
Ok, it's clear.

**Comment by lamdoann** [comment]
For now, you can search file via repo.
Url pattern: owner/repo
Example: lamdoann/serviceDescriptions

**Comment by xapasnon** [comment]
Search works fine. However, when I check one or more entries and press load, nothing happens.

I also think that we should add a "check all" button/option here - that will probably be the default behaviour.

**Comment by lamdoann** [comment]
I added checkall button.
Can you have a check again for loading multiple service descriptions?
It's still working for me.
<img width="1435" alt="screen shot 2019-01-05 at 7 59 27 am" src="https://user-images.githubusercontent.com/22361816/50718224-0418a500-10c0-11e9-97cc-eb0cc83f8339.png">
<img width="1420" alt="screen shot 2019-01-05 at 7 59 49 am" src="https://user-images.githubusercontent.com/22361816/50718227-0418a500-10c0-11e9-8e74-f92d47918f1e.png">

**Comment by xapasnon** [comment]
Confirmed ok!
