### ISSUE TITLE
Table of content and highlighting

### ISSUE THREAD

**Issue by xapasnon** [JohnDoeInvest/ms-visualization#5]
Once we have support for multiple services (https://github.com/JohnDoeInvest/ms-visualization/issues/2#issue-393372539) we'll want a list of the microservice names somewhere.

When clicking on a service, the service will be highlighted (other colour/thicker/Macs to provide input) and potentially put center on the screen.

The purpose is that once we have a big service consisting of many microservices, no matter how good we do the routing, it will be hard to see what one specific service connects to.

**Comment by lamdoann** [comment]
I highlighted the selected service description by making links thicker.
For nodes(icons), we need another highlighted icons.

**Comment by xapasnon** [comment]
Looks good - let's keep this open until I have synced with Macs on design.

**Comment by xapasnon** [comment]
Closing this and creating a new "design overhaul"
