### ISSUE TITLE
Connect specific services to specific sides of the microservice icon

### ISSUE THREAD

**Issue by xapasnon** [JohnDoeInvest/ms-visualization#7]
For consistency and to make it easier to understand the resulting diagram, we assign a "type" to each of the 8 sides of the microservice icon and make the paths/connectors use them. Sides are numbered from 1-8 starting on the "top right" one (think clock-wise):
1: Outgoing connections (i.e. REST calls to other microservices or external systems)
2: Kafka topics - consumer side (i.e paths from topics to this side)
3: Shared services (i.e. Redis)
4: Local storage/databases
5:
6: Kafka topics - producer side (i.e. paths to the "left side" of topics from this side)
7: Incoming connections (i.e. REST endpoints/api)
8: 

The spare ones will surely be used later on...

**Comment by lamdoann** [comment]
It's done.

**Comment by lamdoann** [comment]
I fixed it. It's not perfect for curve of lines. I'll keep updating it more.

**Comment by xapasnon** [comment]
Summary: the resources have been updated with small "paths" with specific ids which allows us to connect the "connectors" to specific points. Right now these paths are small black lines - will need to be re-done when we do new icons.
