### ISSUE TITLE
View only unique shared services

### ISSUE THREAD

**Issue by xapasnon** [JohnDoeInvest/ms-visualization#9]
Now that we support multiple services, a core concept is missing: each shared service that the microservice uses is unique across multiple services. So every microservice that connects to i.e. Redis will have a connector drawn to the one single icon that represents Redis. Same with Kafka topics i.e. the "consumes" and "produces".

**Comment by lamdoann** [comment]
It's done.

**Comment by xapasnon** [comment]
Tested ok!
